version: 3

vars:
  NESTED_MODULES: api
  API_DIRS: '{{.ROOT_DIR}}/api/v1alpha1/...'
  MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
  CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/v1alpha1/...'
  COMPONENTS: 'service-provider-template'
  REPO_NAME: 'https://github.com/openmcp-project/service-provider-template'

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true