name: Renovate Generate

on:
  push:
    branches:
      - "renovate/**"

permissions:
  contents: write

jobs:
  generate:
    uses: openmcp-project/build/.github/workflows/renovate-generate.lib.yaml@c2d37b930a47b3596b919583887f92c7e37987e3 # main
    secrets: inherit
